

services:
  onlinesurvey:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: OnlineSurvey/Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: surveydb
    ports:
      - "5433:5432"
    volumes:
      - survey_data:/var/lib/postgresql/data

volumes:
  survey_data: